fleet_mng/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'fleet_mng'
urlpatterns = [
    path('', views.index, name='index'),

    path('vehicle/', include('fleet_mng.urls_vehicle')),
    path('renter/', include('fleet_mng.urls_renter')),
    path('rent/', include('fleet_mng.urls_rent')),

    path('week/', views.show_week, name='week'),
    re_path(r'^week/(?P<week_rel>-?\d+)/$', views.show_week_rel, name='week_rel'),
    re_path(r'^week/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$', views.show_week_date, name='week_date'),
    re_path(r'^week/ajax/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$', views.ajax_show_week_date,
            name='ajax_week_date'),

    path('user/', include('fleet_mng.urls_user')),

    path('report/', include('fleet_mng.urls_report')),

    path('mileage/', include('fleet_mng.urls_mileage')),
]

fleetmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('fleet_mng.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

fleet_mng/models.py
import datetime

from django.contrib.admin.models import LogEntry, ADDITION, DELETION, CHANGE
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    last_active = models.DateTimeField(null=True, blank=True)

    @staticmethod
    def last_active_all():
        return User.objects.filter(last_active__gte=timezone.now() + datetime.timedelta(minutes=-10)).count()


class TraceableModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    additional_data = {}

    class Meta:
        abstract = True


# dane pojazdu
class Vehicle(TraceableModel):
    # nazwa pojazdu
    name = models.CharField(max_length=193, db_index=True)

    # marka, model, wersja
    brand = models.CharField(max_length=193)
    model = models.CharField(max_length=193)
    generation = models.CharField(max_length=193, blank=True)
    # nr rej.
    registration_number = models.CharField(max_length=193)
    # przebieg
    mileage = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    # badania techniczne
    checkup = models.DateField(blank=True, null=True)
    # ubezpieczenie
    insurance = models.DateField(blank=True, null=True)

    # dłuższy opis
    description = models.TextField(blank=True)

    deleted = models.BooleanField(default=False)

    # ciąg znaków opisujący obiekt
    def __str__(self) -> str:
        return "{0} {1}".format(self.brand, self.registration_number)

    # zwraca True gdy pojazd jest wynajęty
    def is_rented(self) -> bool:
        return Rent.objects.filter(vehicle=self, rented__exact=1).exists()

    # zwraca True gdy pojazd jest wynajęty i minął czas wynajęcia
    def is_not_bring_back(self) -> bool:
        rents = Rent.objects.filter(vehicle=self)
        for rent in rents:
            if rent.is_not_bring_back():
                return True
        return False

    # zwraca True gdy pojazd nie jest wynajęty
    def is_free(self):
        return not self.is_rented()

    # zwraca aktualnych wypożyczających ten pojazd
    def get_current_renters(self):
        return Rent.objects.filter(vehicle=self, rented__exact=1)

    def get_next_mileage_check(self):
        mileage = MileageChecks.objects. \
                      filter(vehicle=self, checked__exact=False). \
                      order_by('next_check'). \
                      values('next_check')[:1]
        if mileage:
            return mileage[0]['next_check']
        return None

    def near_mileage_checkup(self):
        next_m = self.get_next_mileage_check()
        if next_m and (next_m - self.mileage) < 10000:
            return True
        return False

    def get_str(self):
        return str([[self.name,
                     self.brand,
                     self.model,
                     self.generation
                     ],
                    [self.registration_number,
                     self.mileage],
                    [{'checkup': self.checkup,
                      'insurance': self.insurance,
                      }],
                    [{'deleted': self.deleted,
                      'description': self.description,
                      }]
                    ])


class MileageChecks(TraceableModel):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    next_check = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    checked = models.BooleanField(default=False)
    checked_mileage = models.IntegerField(validators=[MinValueValidator(0)], null=True)

    def get_str(self):
        return str([self.vehicle,
                    self.next_check,
                    self.checked,
                    self.checked_mileage,
                    ])


# Wypożyczający
class Renter(TraceableModel):
    # krótka nazwa
    last_name = models.CharField(max_length=193)
    first_name = models.CharField(max_length=193, blank=True)
    # dłuższy opis
    description = models.TextField(blank=True)

    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        tmp = self.first_name
        if not tmp == "":
            tmp = ", " + tmp
        return "{0}{1}".format(self.last_name, tmp)

    def get_str(self):
        return str([self.last_name,
                    self.first_name,
                    self.description,
                    self.deleted,
                    ],
                   )

    def rents(self):
        return Rent.objects.filter(renter=self)

    def rented(self):
        return Rent.objects.filter(renter=self, rented=1)

    def rents_count(self):
        return Rent.objects.filter(renter=self).count()

    def rented_count(self):
        return Rent.objects.filter(renter=self, rented=1).count()


# obiekt wypożyczenia
class Rent(TraceableModel):
    # opis, notatka
    description = models.TextField(blank=True)
    # wypożyczony od (data)
    from_date = models.DateField(default=timezone.now)
    # wypożyczony do (data) zadeklarowane przed oddaniem/ustawione na dzień oddania
    to_date = models.DateField()
    # klucz obcy na pojazd
    vehicle = models.ForeignKey(Vehicle, on_delete=models.DO_NOTHING)
    # klucz obcy na wypożyczającego
    renter = models.ForeignKey(Renter, on_delete=models.DO_NOTHING)
    # flaga czy aktualnie wypożyczony
    rented = models.IntegerField(default=1)

    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0} - {1}: {3}, {4}.".format(self.from_date,
                                             self.to_date,
                                             self.description,
                                             self.vehicle,
                                             self.renter)

    # dodatkowe prawa dostępu
    class Meta:
        permissions = (("can_mark_returned", "Can mark rent as returned"),
                       ("can_show_week", "Can show week view"),
                       )

    # Zwraca True gdy pojazd nie oddany a minęła data wypożyczenia
    def is_not_bring_back(self) -> bool:
        return self.to_date < timezone.now().date() and self.from_date < timezone.now().date() and self.rented == 1

    def get_str(self):
        return str([self.from_date,
                    self.to_date,
                    self.vehicle.id,
                    self.renter.id,
                    self.description,
                    self.rented,
                    self.deleted,
                    ],
                   )


def log_user_entry(request, obj, action_flag, msg):
    LogEntry.objects.log_action(
        user_id=request.user.id,
        content_type_id=ContentType.objects.get_for_model(obj).pk,
        object_id=obj.pk,
        object_repr=str({'username': obj.username,
                         'groups': [gr.id for gr in obj.groups.all()],
                         'is_active': obj.is_active,
                         }),
        action_flag=action_flag,
        change_message=msg)


def log_entry(model: TraceableModel, action_flag):
    user_id = 1
    msg = '[Unknown user.]' + model.get_str()
    if model.additional_data:
        user_id = model.additional_data['request'].user.id
        msg = model.get_str()
    LogEntry.objects.log_action(
        user_id=user_id,
        content_type_id=ContentType.objects.get_for_model(model).pk,
        object_id=model.pk,
        object_repr=msg,
        action_flag=action_flag,
    )


@receiver(post_save)
def post_save_handler(sender, instance, created, using, **kwargs):
    if isinstance(instance, TraceableModel):
        if created:
            log_entry(instance, ADDITION)
        else:
            log_entry(instance, CHANGE)


@receiver(post_delete)
def post_delete_handler(sender, instance, using, **kwargs):
    if isinstance(instance, TraceableModel):
        log_entry(instance, sender, DELETION, "")

fleet_mng/forms.py
from django import forms

from .widgets import BootstrapDateTimePickerInput, BootstrapDatePickerInput
from django.utils.formats import get_format


class DateTimeForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d.%m.%Y %H:%M'],
        widget=BootstrapDateTimePickerInput()
    )


class DateForm(forms.Form):
    date = forms.DateField(
        input_formats=['%d.%m.%Y'],
        widget=BootstrapDatePickerInput()
    )
    print(get_format('DATE_FORMAT'))

fleet_mng/views.py
import datetime

import pytz
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from fleet_mng.models import Rent, Vehicle


# strona główna
# /     => index.html
def index(request):
    return render(request, 'fleet_mng/index.html')


# pokazanie widoku od danego tygodnia (relatywnie w stosunku do aktualnego)
# /week/3   - pokazanie od dnia za 3 tygodnie
# /week/-2  - pokazanie od dnia sprzed 2 tygodni

# /week/<number:week_rel>   =>  week.html
@login_required
@permission_required('fleet_mng.can_show_week')
def show_week_rel(request, week_rel=0):
    show_from = timezone.now() + datetime.timedelta(int(week_rel) * 7)
    return show_week(request, show_from)


# pokazanie widoku od podanej daty
# /week/<year>-<month>-<day>  =>    week.html
@login_required
@permission_required('fleet_mng.can_show_week')
def show_week_date(request, year, month, day):
    naive = timezone.datetime(int(year), int(month), int(day))
    t = pytz.timezone("Europe/Warsaw").localize(naive, is_dst=None)
    return show_week(request, t)


def make_links_for_nav(nav):
    nav['link'] = reverse('fleet_mng:week_date',
                          args=(nav['year'], nav['month'], nav['day'])
                          )
    nav['ajax_link'] = reverse('fleet_mng:ajax_week_date',
                               args=(nav['year'], nav['month'], nav['day'])
                               )


@login_required
@permission_required('fleet_mng.can_show_week')
def ajax_show_week_date(request, year, month, day):
    naive = timezone.datetime(int(year), int(month), int(day))
    t = pytz.timezone("Europe/Warsaw").localize(naive, is_dst=None)
    nav = get_nav_from_date(t)
    make_links_for_nav(nav['prev'])
    make_links_for_nav(nav['prev_week'])
    make_links_for_nav(nav['next'])
    make_links_for_nav(nav['next_week'])
    nav['today_link'] = reverse('fleet_mng:week_date', args=(year, month, day))
    nav['today_ajax_link'] = reverse('fleet_mng:ajax_week_date', args=(year, month, day))
    return JsonResponse(
        {
            'table_html': show_week(request, t, 'fleet_mng/_week_table.html').content.decode('utf-8'),
            'nav': nav
        }
    )


# funkcja podaje wszystkie dni pomiędzy datami (włącznie z końcami)
def date_range(start_date, end_date):
    for n in range(int((end_date - start_date).days) + 1):
        yield start_date + datetime.timedelta(n)


days_names = ['Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So', 'Nd']


def get_nav_from_date(s_date):
    prev_date = s_date + datetime.timedelta(-1)
    prev_week_date = s_date + datetime.timedelta(-7)
    next_date = s_date + datetime.timedelta(+1)
    next_week_date = s_date + datetime.timedelta(+7)
    return {
        'prev': {
            'year': prev_date.year,
            'month': prev_date.month,
            'day': prev_date.day,
        },
        'prev_week': {
            'year': prev_week_date.year,
            'month': prev_week_date.month,
            'day': prev_week_date.day,
        },
        'next': {
            'year': next_date.year,
            'month': next_date.month,
            'day': next_date.day,
        },
        'next_week': {
            'year': next_week_date.year,
            'month': next_week_date.month,
            'day': next_week_date.day,
        }
    }


def compute_week_data(from_range, to_range, show_deleted=False):
    rents = Rent.objects.filter(from_date__lte=to_range).filter(to_date__gte=from_range)

    # fill days
    days = [datetime.date(d.year, d.month, d.day) for d in date_range(from_range, to_range)]
    week_days = [days_names[d.weekday()] for d in days]

    vehicles_data = {}
    vehicles = Vehicle.objects.all()
    if not show_deleted:
        vehicles = vehicles.exclude(deleted=1)

    # initialize vehicles table
    for vehicle in vehicles:
        vehicles_data[vehicle] = [{'present': 0, 'rents': [], 'classes': []} for _ in range(len(days))]

    '''
    f_  -   first
    m_  -   middle
    l_  -   last
    b_  -   not bring back
    r_  -   rented
    n_  -   has note
    '''

    # filling table
    for rent in rents:
        if rent.vehicle.deleted and not show_deleted:
            continue
        last = int((rent.to_date - rent.from_date).days)
        for i, d in enumerate(date_range(rent.from_date, rent.to_date)):
            if d in days:
                tab_item = vehicles_data[rent.vehicle][days.index(d)]
                tab_item['present'] = 1
                tab_item['rents'].append(rent)
                tab_item['classes'].append('m_' + str(rent.id))
                if rent.rented:
                    tab_item['classes'].append('r_' + str(rent.id))
                if rent.is_not_bring_back():
                    tab_item['classes'].append('b_' + str(rent.id))
                if i == 0:
                    tab_item['classes'].append('f_' + str(rent.id))
                    if rent.description:
                        tab_item['classes'].append('n_' + str(rent.id))
                if i == last:
                    tab_item['classes'].append('l_' + str(rent.id))

    return {'days': days, 'week_days': week_days, 'rents': rents, 'vehicles_data': vehicles_data}


# właściwe wywołanie widoku
@login_required
@permission_required('fleet_mng.can_show_week')
def show_week(request, show_from=timezone.now(), template='fleet_mng/week.html'):
    show_to = show_from + datetime.timedelta((4 * 7) - 1)
    from_range = show_from
    to_range = show_to

    week_data = compute_week_data(from_range, to_range)

    return render(request, template,
                  {'days': week_data['days'],
                   'week_days': week_data['week_days'],
                   'rents_list': week_data['rents'],
                   'vehicles_table': week_data['vehicles_data'],
                   'dates': {
                       'from': show_from,
                       'to': show_to,
                   },
                   'nav': get_nav_from_date(show_from),
                   })

fleet_mng/templates/fleet_mng/_base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{% static 'fleet_mng/favicon-32x32.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% if DOCK %}{% static 'fleet_mng/style.min.css' %}{%else%}{% static 'fleet_mng/style.css' %}{%endif%}">
    {% block css_link %}{% endblock %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}">
    <title>{% block title %}MAGMA VMS - Vehicle Management System{% endblock %}</title>
</head>
<body>
  <div class="main-container">
    {% include "fleet_mng/_navbar.html" %}
    {% include "fleet_mng/_userbar.html" %}
    <div class="main-content">
      <div id="content" class="content-display">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

fleet_mng/templates/fleet_mng/_navbar.html
<nav class="nav-side-menu">
    <div class="brand">System Zarządzania Flotą MAGMA</div>

    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <a href="/"><i class="fa fa-dashboard fa-lg"></i> Panel</a>
            </li>
            {% if perms.fleet_mng.view_user %}
            <li>
                <a href="{% url 'fleet_mng:users' %}"><i class="fa fa-user fa-lg"></i> Konta systemowe</a>
            </li>
            {% endif %}
            {% if perms.fleet_mng.view_renter %}
            <li>
              <a href="{% url 'fleet_mng:renters' %}"><i class="fa fa-users fa-lg"></i> Użytownicy</a>
            </li>
            {% endif %}
            {% if perms.fleet_mng.view_vehicle %}
            <li>
              <a href="{% url 'fleet_mng:vehicles' %}"><i class="fa fa-car fa-lg"></i> Pojazdy</a>
            </li>
            {% endif %}
            {% if perms.fleet_mng.can_show_week %}
            <li>
              <a href="{% url 'fleet_mng:week' %}"><i class="fa fa-calendar fa-lg"></i> Plan wypożyczeń</a>
            </li>
            {% endif %}
            {% if perms.fleet_mng.change_rent %}
            <li>
              <a href="{% url 'fleet_mng:report' %}"><i class="fa fa-calendar fa-lg"></i> Raporty</a>
            </li>
            {% endif %}
            {% comment %}
            <!-- <li data-toggle="collapse" data-target="#new" class="collapsed">
              <a href="{% url 'fleet_mng:vehicles' %}"><i class="fa fa-car fa-lg"></i> Pojazdy <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="service">
              <li>New Service 1</li>
              <li>New Service 2</li>
              <li>New Service 3</li>
            </ul> -->
            {% endcomment %}
        </ul>
    </div>
</nav>

fleet_mng/templates/fleet_mng/_userbar.html
<div id="userbar" class="top-bar">
    <span class="active_users">Aktywnych: {{ LAST_ACTIVE_ALL }}</span>
    <span class="beta_indicator">* * * Wersja testowa * * *</span>
    <span class="curr_user">
        {% if user.is_authenticated %}
        <p style="user-ticket">Witaj, {{ user.username }}. <a href="{% url 'logout' %}">Wyloguj</a>.</p>
        {% else %}
        <p style="user-ticket">Witaj nieznajomy. <a href="{% url 'login' %}">Zaloguj się</a>.</p>
        {% endif %}
    </span>
</div>

fleet_mng/templates/fleet_mng/_week_table.html
{% load double_escape %}
    <thead>
        <tr>
            <th rowspan="2">
                Pojazdy
            </th>
            {% for day in days %}{%if forloop.counter0|divisibleby:7 %}
            <th colspan="7">{{ day }}</th>
            {%endif%}
            {% endfor %}
        </tr>
        <tr>
            {% load index %}
            {% for week_day in week_days %}
            <th data-toggle="tooltip" title="{{days|index:forloop.counter0|double_escape}}"><div class="day_name">{{week_day}}</div></th>
            {% endfor %}
        </tr>
      </thead>
      <tbody>
      {% for vehicle, days_data in vehicles_table.items %}
        <tr class="{%if vehicle.is_rented %}is_rented{%endif%}{%if vehicle.is_not_bring_back %} not_bring_back{%endif%}{%if vehicle.is_free %} is_free{%endif%}">
            <th>
                <a href="{% url 'fleet_mng:vehicle' vehicle.id %}"
                   data-toggle="tooltip" data-html="true"
                   title="{{vehicle.name|double_escape}}<br>{{vehicle.brand|double_escape}} {{vehicle.model|double_escape}}{% if vehicle.generation %}<br>
                        {{vehicle.generation|double_escape}}{% endif %}<br>{{vehicle.registration_number|double_escape}}<br>{{vehicle.description|double_escape}}" >
                    {{vehicle.name}}
                </a>
            </th>
            {% for day_d in days_data %}
            <td class="{%if day_d.present %}rent_bar{% else %}no_rent_bar{% endif %}
                {%if vehicle.checkup == days|index:forloop.counter0 %} checkup{% endif %}
                {%if vehicle.insurance == days|index:forloop.counter0 %} insurance{% endif %}
                {% if not perms.fleet_mng.view_renter %} viewonly{% endif %}"
                data-bar="{{ day_d.classes|join:' ' }}"
                {% for rent in day_d.rents %}
                data-bar_tooltip_{{rent.id}}="{{ rent.from_date|double_escape }} - {{ rent.to_date|double_escape }}<br>{{rent.vehicle|double_escape}}<br>{{rent.renter|double_escape}}"
                data-bar_desc_{{rent.id}}="{{rent.description|double_escape}}"
                {% endfor %}
            >
                {%if vehicle.insurance == days|index:forloop.counter0 %}<div class="insurance"  data-toggle="tooltip" data-html="true" data-placement="left"
                                                                        title="Ubezpieczenie.<br>{{vehicle|double_escape}}<br>{{vehicle.insurance|double_escape}}"></div>{% endif %}
                {%if vehicle.checkup == days|index:forloop.counter0 %}<div class="checkup"  data-toggle="tooltip" data-html="true" data-placement="left"
                                                                        title="Przegląd techniczny.<br>{{vehicle|double_escape}}<br>{{vehicle.checkup|double_escape}}"></div>{% endif %}
            </td>
            {% endfor %}
        </tr>
      {% endfor %}
      </tbody>

fleet_mng/templates/fleet_mng/index.html
{# Strona główna - index.html #}
{% extends "fleet_mng/_base.html" %}
{% block content %}
<h2>Witamy w MAGMA VMS - Vehicle Management System.</h2>
{% if user.is_authenticated %}
<p>Przejdź do <a href="{% url 'fleet_mng:week' %}"><i class="fa fa-calendar fa-lg"></i> planu wypożyczeń</a></p>
{% else %}
<p><a href="{% url 'login' %}"><button type="submit" class="btn btn-primary"><i class="fa fa-sign-in fa-lg"></i> Zaloguj się</button></a></p>
{% endif %}
{% endblock %}

fleet_mng/templates/fleet_mng/rent.html
{# Wyświetlenie danych konkretnego wypożyczenia #}
{% extends "fleet_mng/_base.html" %}
{% block content %}
{% load static %}
<div class="buttons_row">
    <a href="{% url 'fleet_mng:week' %}">
        <button class="btn btn-primary btn-sm" type="button"><i class="fa fa-arrow-left fa-lg"></i></button>
    </a>
</div>

<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered" id="items-table">
            <tbody>
            <tr>
                <th>Wypożyczony:</th>
                <td>{{ rent.from_date }}</td>
            </tr>
            <tr>
                {%if rent.rented %}
                <th>Termin oddania:</th>
                {%else%}
                <th>Oddano:</th>
                {% endif %}
                <td>
                    <div class="{%if rent.is_not_bring_back %}not_bring_back{%endif%}">
                        {{ rent.to_date }}
                    </div>
                </td>
            </tr>
            <tr>
                <th>Pojazd:</th>
                <td><a href="{% url 'fleet_mng:vehicle' rent.vehicle.id %}">{{ rent.vehicle }}</a></td>
            </tr>
            <tr>
                <th>Używany przez:</th>
                <td>
                    {% if perms.fleet_mng.view_renter %}
                    <a href="{% url 'fleet_mng:renter' rent.renter.id %}">{{ rent.renter }}</a>
                    {% else %}
                    {{ rent.renter }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Uwagi:</th>
                <td>{{ rent.description }}</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="buttons_row">
    {% if perms.fleet_mng.change_rent %}
    <a href="{% url 'fleet_mng:rent_edit' rent.id%}">
        <button type="submit" class="btn btn-primary">Edytuj</button>
    </a>
    {% endif %}
    {% if perms.fleet_mng.can_mark_returned and rent.rented == 1 %}
    <script src="{% if DOCK %}{% static 'fleet_mng/form_helpers.min.js' %}{%else%}{% static 'fleet_mng/form_helpers.js' %}{%endif%}"></script>
    <form method=post name="delete_form" action="{% url 'fleet_mng:rent_bring_back' rent.id %}"
          onsubmit="_delete(event,this,'Potwierdź zwrot pojazdu.');">
        {% csrf_token %}
        <input type=hidden name="confirm" value="0"/>
        <button type="submit" class="btn btn-primary">Zwróć</button>
    </form>
    {% endif %}
</div>
{% endblock %}

fleet_mng/templates/fleet_mng/renters.html
{# Wyświetlenie listy wypożyczających #}
{% extends "fleet_mng/_base.html" %}
{% block content %}
<div class="buttons_row">
    <a href="{% url 'fleet_mng:week' %}">
        <button class="btn btn-primary btn-sm" type="button"><i class="fa fa-arrow-left fa-lg"></i></button>
    </a>

    {% if perms.fleet_mng.add_renter %}
    <a href="{% url 'fleet_mng:renter_new' %}" class="btn">
        <button class="btn btn-primary btn-sm" type="button">Nowy użytkownik</button>
    </a>
    {% endif %}
</div>

{% if renter_list %}
<ul class="item-list">
    {% for renter in renter_list %}
    {% if perms.fleet_mng.change_renter or not renter.deleted %}
    <li class="list-group-item list-group-item-action{% if renter.deleted %} item_deleted{% endif %}{% if renter.rented_count %} has_rents{% endif %}">
        <a href="{% url 'fleet_mng:renter' renter.id %}">
            {{ renter }}
        </a>
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>Brak użytkowników.</p>
{% endif %}
{% endblock %}

fleet_mng/templates/fleet_mng/rents.html
{# Wyświetlenie listy wypożyczeń #}
{% extends "fleet_mng/_base.html" %}
{% block content %}
<div class="buttons_row">
    <a href="{% url 'fleet_mng:week' %}">
      <button class="btn btn-primary btn-sm" type="button"><i class="fa fa-arrow-left fa-lg"></i></button>
    </a>

    {% if perms.fleet_mng.add_rent %}
    <a href="{% url 'fleet_mng:rent_form' %}" class="btn">
      <button class="btn btn-primary btn-sm" type="button">Nowe wypożyczenie</button>
    </a>
    {% endif %}
</div>
{% if rent_list %}
<ul>
    {% for rent in rent_list %}
    <li class="list-group-item list-group-item-action {% if not rent.rented %} item_deleted{% endif %}">
      <a href="{% url 'fleet_mng:rent' rent.id %}">{{ rent }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Brak wypożyczeń.</p>
{% endif %}
{% endblock %}